name: My Deploy
on: push
jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
      - uses: actions/checkout@v3
      - name: Install dependencies
      - run: npm ci
      - name: build
      - run: npm run build

